# Generated by Django 5.0.6 on 2024-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PC', 'PC'), ('PS', 'PlayStation'), ('XBOX', 'Xbox'), ('NINTENDO', 'Nintendo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
