# Generated by Django 5.0.6 on 2024-05-23 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0002_alter_device_device_type_alter_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='available',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
