# Generated by Django 5.0.6 on 2024-05-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0003_remove_device_available_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
